name: Build and Deploy Faustus Front

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for accurate git diff

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Check for Changes in Theme or Widget
      - name: Check for Theme Changes
        id: theme_changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^theme/' || echo "no_theme_changes" > /tmp/no_theme_changes

      - name: Check for Widget Changes
        id: widget_changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^widgets/' || echo "no_widget_changes" > /tmp/no_widget_changes

      # Step 4: Install dependencies and build the React widget if it has changed
      - name: Install dependencies and build widget
        if: steps.widget_changes.outputs.widget_changes != 'no_widget_changes'
        run: |
          cd widgets/faustus-front
          npm install
          npm run build

      # Step 5: Upload Theme Files via SFTP if there are changes in theme/
      - name: Upload Theme Files via SFTP
        if: steps.theme_changes.outputs.theme_changes != 'no_theme_changes'
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          # Ensure the theme directory exists
          sshpass -p "${{ secrets.SFTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SFTP_USERNAME }}@ssh.strato.de "mkdir -p /STRATO-apps/wordpress_01/app/wp-content/themes/faustus-club-theme/"
          # Upload theme files
          sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -p 22 ${{ secrets.SFTP_USERNAME }}@ssh.strato.de <<EOF
          put -r theme/* /STRATO-apps/wordpress_01/app/wp-content/themes/faustus-club-theme/
          bye
          EOF

      # Step 6: Upload Widget Build Files via SFTP if there are changes in widgets/faustus-front/
      - name: Upload Widget Files via SFTP
        if: steps.widget_changes.outputs.widget_changes != 'no_widget_changes'
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -p 22 ${{ secrets.SFTP_USERNAME }}@ssh.strato.de <<EOF
          put -r widgets/faustus-front/public/* /STRATO-apps/wordpress_01/app/wp-content/plugins/faustus-front/public/
          bye
          EOF
 