name: Build and Deploy Faustus Front

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies and build the project
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build

      # Step 4: Archive the build output
      - name: Archive build output
        run: tar -czvf build.tar.gz -C build .

      # Step 5: Upload the tarball to Strato server
      - name: Upload Tarball to Strato
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ssh.strato.de
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "build.tar.gz"  # Upload the tar archive
          target: "/STRATO-apps/wordpress_01/app/wp-content/plugins/faustus-front/"  # Only the directory path
          overwrite: true
          debug: true

      # Step 6: Extract and Verify Files on Server
      - name: Extract and Verify Files on Server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ssh.strato.de
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            echo "Navigating to the target directory..."
            cd /STRATO-apps/wordpress_01/app/wp-content/plugins/faustus-front || { echo "Directory not found"; exit 1; }
            echo "Extracting the tarball..."
            tar -xzvf build.tar.gz || { echo "Extraction failed"; exit 1; }
            echo "Cleaning up..."
            rm build.tar.gz
            echo "Deployment complete."
